name: ReportPE
author: StuckDexter,GamerBOXone
version: 2.0
api: [3.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5]
main: StuckDexter\report
website: https://twitter.com/dexterhd5
description: Report players with /report! Authors: StuckDexter GamerBOXone ! Do not change this!
commands: 
  report:
    description: Report a player
permission:
  report.recive:
    default: op